# Site settings
title: Aiden's Blog
header-img: img/home-bg.jpg
email: aiden_zhang2012@163.com
description: "I am a Senior Software Engineering at the <a href='http://www.iqiyi.com'>iQiyi.com</a>, Graduated from Beijing University of Technology. Forcus on backend development. This is a blog about software, knowledge sharing and bloger's boring life. Not necessarily in that order. "
baseurl: ""
url: "http://knightaiden.github.io"
github_username:  knightaiden
facebook_username:  张哲
email_username:  aiden_zhang2012@163.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
